#这是一个sfz尾号计算器
a=input('请输入第1位：')
b=input('请输入第2位：')
c=input('请输入第3位：')
d=input('请输入第4位：')
e=input('请输入第5位：')
f=input('请输入第6位：')
g=input('请输入第7位：')
h=input('请输入第8位：')
i=input('请输入第9位：')
j=input('请输入第10位：')
k=input('请输入第11位：')
l=input('请输入第12位：')
m=input('请输入第13位：')
n=input('请输入第14位：')
o=input('请输入第15位：')
p=input('请输入第16位：')
q=input('请输入第17位：')
z=(int(a)*7+int(b)*9+int(c)*10+int(d)*5+int(e)*8+int(f)*4+int(g)*2+int(h)*1+int(i)*6+int(j)*3+int(k)*7+int(l)*9+int(m)*10+int(n)*5+int(o)*8+int(p)*4+int(q)*2)%11#求余数
y=('1','0','X','9','8','7','6','5','4','3','2')#给运算结果予对应的赋值
x=y[z]
print('最后一位为：',x)